### ISSUE TITLE
--backup-file does not save entire name so restore fails

### ISSUE THREAD

**Issue by xbmcnut** [tasmota/decode-config#10]
**Describe the bug**
_A clear and concise description of what the bug is._
Using `decode-config_win64 -d 10.0.1.67 --backup-file Config_@f_@v` produces a file called `Config_Sonoff_S20_6.6.0.json`. Subsequently using `decode-config_win64 -d 10.0.1.67 --restore-file Config_@f_@v `produces and error that states:

> ERROR 3 (@3125): File '.\Config_Sonoff_6.6.0.json' not found

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Program parameter:_
_2. Result:_
As above

**Expected behavior**
_A clear and concise description of what you expected to happen._
Restore would locate correct file name

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```

decode-config_win64 v8.1.0.0 [00062] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.8
Platform: Windows-10-10.0.18362-SP0 - AMD64
OS:       Windows 10 10.0.18362
Time:     2020-03-18 19:46:21
```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```

{"SensorBits1": {}, "bootcount": 14, "cfg_crc": "0xefa0", "cfg_holder": 4617, "cfg_size": 3584, "displays": "0xffffffff", "energy_kWhtotal_time": 1567749179, "flag": {}, "flag2": {"axis_resolution": 0}, "flag3": {}, "header": {"data": {"crc": "0xefa0", "size": 3584, "version": "0x6060000"}, "format": {"jsoncompact": false, "jsonhidepw": false, "jsonindent": null, "jsonsort": true}, "os": ["AMD64", "Windows", "10", "10.0.18362", "Windows-10-10.0.18362-SP0"], "python": "3.6.8", "script": {"name": "decode-config.py", "version": "8.1.0.0 [00062]"}, "template": {"crc": "0xefa0", "size": 3584, "version": "0x605000f"}, "timestamp": "2020-03-18 06:48:43"}, "last_module": 255, "monitors": "0xffffffff", "rgbwwTable": [255, 255, 255, 255, 255], "save_flag": 44, "sensors": ["0xffffffff", "0xffffffff", "0xffffffff"], "sps30_inuse_hours": 0, "timezone_minutes": 0, "version": "0x6060000"}

```

**Additional context**
_Add any other context about the problem here._

**Comment by xbmcnut** [comment]
P.S Using this tool and methodology, is it possible to upgrade from 6.6.0 to 8,1,0 directly?

**Comment by curzon01** [comment]
> P.S Using this tool and methodology, is it possible to upgrade from 6.6.0 to 8.1.0 directly?

Yes, but an OTA update from 6.x to 8.x will fail (the addresses of the Tasmota settings data have changed between the versions and only the [migration path](https://tasmota.github.io/docs/#/Upgrading?id=migration-path) correctly takes care of the values from the previous versions).
If you are unlucky, after the OTA upgrade at the new setting addresses is garbadge so Tasmota keeps constantly rebooting and therefore the boot loop detection (see [SetOption36](https://tasmota.github.io/docs/#/Commands?id=setoption36)) will reset your settings and the device loses the WiFi connection.

The safest way from 6.x to 8.x is 
a) using migration path or 
b) backup the 6.x data, upgrade via serial programming and restore the 6.x data.

**Comment by curzon01** [comment]
> Using `decode-config_win64 -d 10.0.1.67 --backup-file Config_@f_@v` produces a file called `Config_Sonoff_S20_6.6.0.json`. Subsequently using `decode-config_win64 -d 10.0.1.67 --restore-file Config_@f_@v `produces and error that states:

issue already fixed in the [current developer branch](https://github.com/tasmota/decode-config/tree/development).

There are no binaries for this, updated binaries will only be available with the next official Tasmota release, so that the current version can only be used as a Python script.
