### ISSUE TITLE
When converting a dmp file to json, file name does not follow dmp file

### ISSUE THREAD

**Issue by xbmcnut** [tasmota/decode-config#11]
**Describe the bug**
_A clear and concise description of what the bug is._
When using `decode-config.py -f Config_washer_7021_8.1.0.dmp --backup-file Config-@f --backup-type json`, the created file is name `Config-Washing_Machine.json` instead of `Config_Washing_Machine.json` (replaces underscore with hyphen).

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Program parameter:_
_2. Result:_

**Expected behavior**
_A clear and concise description of what you expected to happen._
json file to match source filename.

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```

decode-config.py v8.1.0.10 [00085] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.7.7
Platform: Windows-10-10.0.18362-SP0 - AMD64
OS:       Windows 10 10.0.18362
Time:     2020-03-19 22:18:33

```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```
{"bootcount": 174, "cfg_crc": "0x1d7d", "cfg_crc32": "0xe700f372", "cfg_holder": 4617, "cfg_size": 4096, "cfg_timestamp": 1584500617, "displays": "0xffffffff", "energy_kWhtotal_time": 1543840427, "flag2": {"axis_resolution": 0}, "flag4": "0x00000000", "header": {"data": {"crc": "0x433d", "crc32": "0xe700f372", "size": 4096, "version": "0x8010000"}, "format": {"jsoncompact": false, "jsonhidepw": false, "jsonindent": null, "jsonsort": true}, "os": ["AMD64", "Windows", "10", "10.0.18362", "Windows-10-10.0.18362-SP0"], "python": "3.7.7", "script": {"name": "decode-config.py", "version": "8.1.0.10 [00085]"}, "template": {"crc": "0x1d7d", "crc32": "0xe700f372", "size": 4096, "version": "0x8010000"}, "timestamp": "2020-03-18 03:03:37"}, "last_module": 0, "monitors": "0xffffffff", "rgbwwTable": [255, 255, 255, 255, 255], "save_flag": 1312, "sps30_inuse_hours": 0, "timezone_minutes": 0, "version": "0x8010000"}

```

**Additional context**
_Add any other context about the problem here._

**Comment by xbmcnut** [comment]
Furthermore, if I try to restore the constructed json file by renaming it, I get the following error.
```
c:\Python\Python37>decode-config.py -d 10.0.1.176 --restore-file Config-Washing_Machine.json
WARNING 9: file '.\Config-Washing_Machine.json' - {'adc_param_type': 51} (valid range exceeding)
```

**Comment by curzon01** [comment]
> When using `decode-config.py -f Config_washer_7021_8.1.0.dmp --backup-file Config-@f --backup-type json`, the created file is name `Config-Washing_Machine.json` instead of `Config_Washing_Machine.json` (replaces underscore with hyphen).

not a bug, as designed
if you want to have `Config_Washing_Machine.json` the correct parameter is `--backup-file Config_@f` (hyphen are not replaced)

**Comment by curzon01** [comment]
> Furthermore, if I try to restore the constructed json file by renaming it, I get the following error.
> 
> ```
> c:\Python\Python37>decode-config.py -d 10.0.1.176 --restore-file Config-Washing_Machine.json
> WARNING 9: file '.\Config-Washing_Machine.json' - {'adc_param_type': 51} (valid range exceeding)
> ```

[AdcParam](https://tasmota.github.io/docs/#/Commands?id=adcparam) <x> is limited to 2-7.
Correct your JSON or ignore the warning during restore by using `--ignore-warnings`

Reason might be garbadge in your Tasmota device config after an upgrade
Suggestion: Backup config, use Tasmota [Reset](https://tasmota.github.io/docs/#/Commands?id=reset) (e.g. param 5) and then restore config. Then it's clean.

**Comment by xbmcnut** [comment]
Thanks for the prompt reply and feedback. Much appreciated. I'm slowly getting my head around it.

**Comment by curzon01** [comment]
your are welcome - add. note regarding suggestion: 

> Suggestion: Backup config **using JSON format**...

 (it does not work when you use one of the binary format)

**Comment by xbmcnut** [comment]
So if I'm upgrading from older versions to 8.1, always use your tool to create a JSON file first rather than downloading a .dmp file from the GUI?

**Comment by xbmcnut** [comment]
Sorry to be a pain, but before I used your suggested migration method (thank you for that), I saved a dmp file (6.6.0) and have now converted that to a JSON file using your tool. If I upload the dmp file directly to the freshly reset device now running 8.1.0, everything is restored. If however I use this tool to upload the JSON version, I always get `WARNING 9: file '.\Config_Washing_Machine.json' - {'adc_param_type': 51} (valid range exceeding)`

Am I missing something? Sorry, but want to make a help video for my tubers but struggling a bit.

**Comment by xbmcnut** [comment]
Are, here we go. A bit more context. Used `--ignore-warnings` and got:
`WARNING 9: Restore file '.\Config_Washing_Machine.json' contains obsolete name 'novasds_period', skipped`

**Comment by curzon01** [comment]
> Are, here we go. A bit more context. Used `--ignore-warnings` and got:
> `WARNING 9: Restore file '.\Config_Washing_Machine.json' contains obsolete name 'novasds_period', skipped`

novasds_period does not exist anymore in 8.1, delete this line from json. I will change decode-config so obsolete names will not stop restore anymore

**Comment by curzon01** [comment]
sorry, ignore obsolete names is already in - it does what it says when using --ignore-warnings - `skipped`

**Comment by xbmcnut** [comment]
Thanks! All very helpful.
