### ISSUE TITLE
Restore drops '0' in version number. Won't complete

### ISSUE THREAD

**Issue by xbmcnut** [tasmota/decode-config#12]
**Describe the bug**
_A clear and concise description of what the bug is._
Sorry! Last one I promise. Backup and restores going sweetly now but when I do this:
`decode-config.py -d 10.0.1.164 --backup-file Config_@f_@v`, it creates a file called `Config_Office_RGB_Bulb_8.1.0` which is great. When I try to restore though, I get the following error.
```
c:\Python\Python37>decode-config.py -d 10.0.1.164 --restore-file Config_Office_RGB_Bulb_8.1.0
ERROR 3 (@3297): File '.\Config_Office_RGB_Bulb_8.1.json' not found
```

Seems the 0 is being ignored.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Program parameter:_
_2. Result:_
As above
**Expected behaviour**
_A clear and concise description of what you expected to happen._
Want to be able to copy the filename for the restore command without having to rename as storing backups with version numbers intact is important.
**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```

decode-config.py v8.1.0.10 [00085] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.7.7
Platform: Windows-10-10.0.18362-SP0 - AMD64
OS:       Windows 10 10.0.18362
Time:     2020-03-20 14:31:05

```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```

{"bootcount": 63, "cfg_crc": "0xcffc", "cfg_crc32": "0xb8910bf8", "cfg_holder": 4617, "cfg_size": 4096, "cfg_timestamp": 1584615899, "displays": "0xffffffff", "energy_kWhtotal_time": 1583301699, "flag2": {"axis_resolution": 0}, "flag4": "0x00000000", "header": {"data": {"crc": "0x1b44", "crc32": "0xb8910bf8", "size": 4096, "version": "0x8010000"}, "format": {"jsoncompact": false, "jsonhidepw": false, "jsonindent": null, "jsonsort": true}, "os": ["AMD64", "Windows", "10", "10.0.18362", "Windows-10-10.0.18362-SP0"], "python": "3.7.7", "script": {"name": "decode-config.py", "version": "8.1.0.10 [00085]"}, "template": {"crc": "0xcffc", "crc32": "0xb8910bf8", "size": 4096, "version": "0x8010000"}, "timestamp": "2020-03-19 11:04:59"}, "last_module": 255, "monitors": "0xffffffff", "rgbwwTable": [255, 255, 255, 255, 255], "save_flag": 616, "sps30_inuse_hours": 0, "timezone_minutes": 0, "version": "0x8010000"}

```

**Additional context**
_Add any other context about the problem here._

**Comment by curzon01** [comment]
how should the program differentiate whether appened `.0` belongs to the file name or is a user-selected extension?

You are using the program with the automatic extension switched on (that is the case when parameter `--no-extension` is not used), so dc first try to separate the extension set by the user and then append the automatic extension (filetype = json) so the process is
a) `Config_Office_RGB_Bulb_8.1.0` becomes `Config_Office_RGB_Bulb_8.1`
b) `Config_Office_RGB_Bulb_8.1` becomes `Config_Office_RGB_Bulb_8.1.json`

There are two ways to avoid all of this:

- if the restore file name is given as full name, the extension should also be given, i.e. `decode-config.py -d 10.0.1.164 --restore-file Config_Office_RGB_Bulb_8.1.0.json`

- file names macros @ are also allowed for restore, the program gets the necessary information from your `-d device` or `-f file`: `decode-config.py -d 10.0.1.164 --restore-file Config_@f_@v`

**Comment by xbmcnut** [comment]
That's awesome. Thank you for the clarification.
