### ISSUE TITLE
Windows 64-Bit exe fails on dump command with stack trace 

### ISSUE THREAD

**Issue by buenyamin-olgun** [tasmota/decode-config#13]
**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Program parameter:_. \decode-config_win64.exe -d < device ip > --backup-file Config-@f --backup-type json
_2. Result:_
![image](https://user-images.githubusercontent.com/32687653/77595166-be304280-6ef8-11ea-9160-ef0cb1555fba.png)

**Expected behavior**
_A clear and concise description of what you expected to happen._

According to https://tasmota.github.io/docs/#/Upgrading?id=decode-config-tool the command should create a new backup straight from the device.

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```
decode-config_win64.exe v8.2.0.0 [00063] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.8
Platform: Windows-10-10.0.18362-SP0 - AMD64
OS:       Windows 10 10.0.18362
Time:     2020-03-26 00:26:18

```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```
{
   "bootcount":12,
   "cfg_crc":"0x4c46",
   "cfg_crc32":"0x543b80aa",
   "cfg_holder":4617,
   "cfg_size":4096,
   "cfg_timestamp":1584881422,
   "displays":"0xffffffff",
   "energy_kWhtotal_time":1579366855,
   "flag2":{
      "axis_resolution":0
   },
   "flag4":"0x00000000",
   "header":{
      "data":{
         "crc":"0x2c6a",
         "crc32":"0x543b80aa",
         "size":4096,
         "version":"0x8010000"
      },
      "format":{
         "jsoncompact":false,
         "jsonhidepw":false,
         "jsonindent":null,
         "jsonsort":true
      },
      "os":[
         "AMD64",
         "Windows",
         "10",
         "10.0.18362",
         "Windows-10-10.0.18362-SP0"
      ],
      "python":"3.6.8",
      "script":{
         "name":"decode-config.py",
         "version":"8.2.0.0 [00063]"
      },
      "template":{
         "crc":"0x4c46",
         "crc32":"0x543b80aa",
         "size":4096,
         "version":"0x8010000"
      },
      "timestamp":"2020-03-22 12:50:22"
   },
   "last_module":0,
   "monitors":"0xffffffff",
   "rgbwwTable":[
      255,
      255,
      255,
      255,
      255
   ],
   "save_flag":1045,
   "sps30_inuse_hours":0,
   "timezone_minutes":0,
   "version":"0x8010000"
}
```

**Additional context**
_Add any other context about the problem here._

**Comment by curzon01** [comment]
Does  `\decode-config_win64.exe -d<device ip>` working on this device?

Does  `\decode-config_win64.exe -d<device ip> -o test` working on this device?

What's the FriendlyName1 of this device?

**Comment by buenyamin-olgun** [comment]
Yes, ``-d <device ip>`` works, but appending ``-o test`` does not work.
Throws the same error as in the picture above.

FriendlyName1 is ``kueche-jalousie``
