### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by anwa** [tasmota/decode-config#15]
**Describe the bug**
`./decode-config.py -v --device 10.10.80.224`
INFO: Load data from device '10.10.80.224'
INFO: Device '10.10.80.224' is using Tasmota v8.2.0.4 on ESP32
Traceback (most recent call last):
  File "./decode-config.py", line 3943, in <module>
    print(get_jsonstr(CONFIG['mapping'], ARGS.jsonsort, ARGS.jsonindent, ARGS.jsoncompact))
  File "./decode-config.py", line 1741, in get_jsonstr
    for key in configmapping:
RuntimeError: dictionary keys changed during iteration

The same error on tasmota 7.x devices.

**To Reproduce**
The Problem is comming with commit:
SHA-1: 3ed9f48f7100a28aa30736ca1818353af26847bb
* Change JSON output key sort case independently
Earlier versions are working.

**Expected behavior**
Output of json :)

**Version Information (please complete the following information):**
decode-config.py v8.2.0.5 [00127] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.8.2
Platform: Linux-5.4.0-26-generic-x86_64-with-glibc2.29 - x86_64
OS:       Linux 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020
Time:     2020-04-27 08:30:51

**Comment by curzon01** [comment]
should be fixed with latest commit (v8.2.0.5 [00129])

**Comment by anwa** [comment]
You are amazing! Thank you very much :)
The issue is solved for me.
