### ISSUE TITLE
Incorrect decoding (it seems) of Sensor29 configuration

### ISSUE THREAD

**Issue by garci66** [tasmota/decode-config#16]
**Describe the bug**
When reading back a device configured to use Sensor29(https://tasmota.github.io/docs/MCP230xx/)  the config data displayed is wrong for ports 8-15.

Using  using tasmota 8.2.0 compiled as tasmota-sensors with only this setting: `#define USE_MCP230xx`

The output is shown as follows: 
```
decode-config_win64.exe -d 192.168.1.216 -T cmnd
  <snip>
  Sensor29 0,2,1,1
  Sensor29 1,2,1,1
  Sensor29 2,2,1,1
  Sensor29 3,2,1,1
  Sensor29 4,2,1,1
  Sensor29 5,2,1,1
  Sensor29 6,2,1,1
  Sensor29 7,2,1,1
  Sensor29 8,0,0,0
  Sensor29 9,7,1,3
  Sensor29 10,7,1,3
  Sensor29 11,6,1,3
  Sensor29 12,3,0,3
  Sensor29 13,0,0,0
  Sensor29 14,0,0,0
  Sensor29 15,7,1,3
```

While all the lines should be identical (which is what I configured on the device).

**To Reproduce**
_Steps to reproduce the behavior:_
 - Configure tasmota with support for MCP230xx
 - Configure Sensors as follows `Sensor29 0,2,1,1` 
 - Repeat for all 16 inputs of Sensor29 `Sensor29 1,2,1,1` .. etc.
 - Re-read the configuration using `decode-config_win64.exe -d 192.168.1.216 -T cmnd`
 - See that ports 8-15 are wrong - The ones for port 0-7 are correct.

**Expected behavior**
The proper config is shown for all 16 ports and not just the lower 8 

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```
C:\Users\garci\Downloads\tasmota>decode-config_win64.exe -VV
decode-config_win64.exe v8.2.0.0 [00063] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.8
Platform: Windows-10-10.0.18362-SP0 - AMD64
OS:       Windows 10 10.0.18362
Time:     2020-05-03 20:02:36
```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
`decode-config_win64.exe -d 192.168.1.216 -g System`

```
{"bootcount": 9, "bootcount_reset_time": 1587951307, "cfg_crc": "0x2607", "cfg_crc32": "0x83687e57", "cfg_holder": 4617, "cfg_size": 4096, "cfg_timestamp": 1588457925, "displays": "0xffffffff", "energy_kWhtotal_time": 1587951307, "flag2": {"axis_resolution": 0}, "header": {"data": {"crc": "0xbd8b", "crc32": "0x83687e57", "size": 4096, "version": "0x8020000"}, "format": {"jsoncompact": false, "jsonhidepw": false, "jsonindent": null, "jsonsort": true}, "os": ["AMD64", "Windows", "10", "10.0.18362", "Windows-10-10.0.18362-SP0"], "python": "3.6.8", "script": {"name": "decode-config.py", "version": "8.2.0.0 [00063]"}, "template": {"crc": "0x2607", "crc32": "0x83687e57", "size": 4096, "version": "0x8020000"}, "timestamp": "2020-05-02 22:18:45"}, "last_module": 255, "monitors": "0xffffffff", "rgbwwTable": [255, 255, 255, 255, 255], "save_flag": 38, "sps30_inuse_hours": 0, "timezone_minutes": 0, "version": "0x8020000"}
```

**Comment by curzon01** [comment]
pls try latest [dev release](https://github.com/tasmota/decode-config/tree/development) v8.2.0.6 [00134]

**Comment by garci66** [comment]
Looks good now! Thanks!
