### ISSUE TITLE
Python error (Windows Executable)

### ISSUE THREAD

**Issue by schrej-zz** [tasmota/decode-config#21]
When executing decode-config_win64.exe I get the error
` Error loading Python DLL C:\Users\ADMIN~1\AppDataLocal\Temp\....\python36.dll`
I have python 3.8. installed, but that should not matter for an executable.

**Comment by curzon01** [comment]
The request to fill the issue template is not a nuisance but a necessity to avoid standard queries about version number, command line to reproduce etc...

**Comment by schrej-zz** [comment]
I was able to file the issue without going through your bug/feature pages and therefore haven't seen your issue template for any reason.
Don't worry, closing the issue.

**Comment by edizius** [comment]
I have the same problem, but I do not see a solution. Is it necessary to install Python 3.6?

**Comment by curzon01** [comment]
see #22

**Comment by edizius** [comment]
partially, I would say. Yes, for me is solved by using python script, but executable does not work. not necessary for me anyhow, so closed is for me personaly fine. but adding "py " in front of the exe does not work

**Comment by curzon01** [comment]
exe might not work for people who already installed python with another version, that's a result of pyinstaller which makes the exec but for those the exe isn't intended for. If already have python installed, use the python version.
