### ISSUE TITLE
Parameters are not used / forwarded

### ISSUE THREAD

**Issue by edizius** [tasmota/decode-config#22]
OS: Win7 64bit
Python: 3.8 (latest compatible with Win7)
Problem with: Decode-config.py +cmd / powershell / powershell 32 bit with / without admin privileges

Command -m pip install ... Was executed fine

**Describe the bug**
All parameters forwarded like -s / --source are not recognized, and only the short info about the commands to be used is plotted (like only "decode-config.py" is executed.

Therefore also no json file etc. Is created or plotted.

**To Reproduce**
_Steps to reproduce the behavior: Win7? Phyton 3.8?
_1. Program parameter: any. E.g. "decode-config.py -s 192.168.0.123"
_2. Result: no config file is created

**Expected behavior**
Dmp file / config from device can be decoded.

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
Latest from git-master

>>> paste decode-config.py output here <<<
Like the output if no parameter is added
```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```
doesn't work

>>> paste decode-config.py output here <<<

```

**Additional context**
_Add any other context about the problem here._

**Comment by curzon01** [comment]
use additional -o parameter to create a backup file, -s only does not create any file

**Comment by edizius** [comment]
hi,
today it worked by adding "py " in front of the command.
So with command "py decode-config.py --source 192.168.0.123 --backup-file Config-@f" it now worked to create the json file
