### ISSUE TITLE
conversion between versions 6.5.0.16 -> to 8.5.1 not possible

### ISSUE THREAD

**Issue by edizius** [tasmota/decode-config#23]
**Describe the bug**
By executing command `py decode-config.py -s tasmota_8.5.1.dmp -i config-tasmota_6.5.0.16.json` the execution fails with:
```
WARNING 9 (@3734): file 'config-tasmota_6.5.0.16.json' array 'energy_power_delta' couldn't restore, format has changed! Restore value contains (class 'int') but an array of size [3] is expected
Premature exit - Restore data error #9"
```

**To Reproduce**
_backup file with 6.5.0.16, update to 8.5.1 and restore the backup
_1. Program parameter:_ -s [TARGET] -i [SOURCE]
_2. Result:_ WARNING 9 (@3734): file 'config-tasmota_6.5.0.16.json' array 'energy_power_delta' couldn't restore, format has changed! Restore value contains (class 'int') but an array of size [3] is expected
Premature exit - Restore data error #9"

**Expected behavior**
conversion between formats is executed (`can convert data from older Tasmota versions (from version v5.10.0) to a newer one and vice versa`)

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```
v8.5.1 [00069]
```

**Comment by curzon01** [comment]
It is what is says, 

> 'energy_power_delta' couldn't restore, format has changed!

[--ignore-warnings](https://github.com/tasmota/decode-config#program-parameter-list) is your friend

**Comment by edizius** [comment]
yes, thanks, --ignore-warnings did the trick. thank you very much
