### ISSUE TITLE
Error when trying to restore saved config in JSON

### ISSUE THREAD

**Issue by bogorad** [tasmota/decode-config#24]
**Describe the bug**
When I try to restore the previously saved config (JSON), I get these errors:

"zb_topic_fname" is deprecated 
"zigbee_distinct_topics" is deprecated 

**To Reproduce**
1. command "SetOption100 1"
2. command "SetOption112 1"
3. decode-config_win64.exe -s admin:pw@192.168.86.xx -o zig.json 
4. decode-config_win64.exe -s admin:pw@192.168.86.xx -i zig.json 

**Expected behavior**
Should work.

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```
decode-config_win64.exe v9.1.0 [a93dad9] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.8
Platform: Windows-10-10.0.19041-SP0 - AMD64
OS:       Windows 10 10.0.19041
Time:     2020-11-30 21:36:32

```

**Comment by curzon01** [comment]
pls provide
- the origin error output without any abbreviations (error msg completely)
- the output of `decode-config_win64.exe -s admin:pw@192.168.86.xx -g system`

**Comment by bogorad** [comment]
Turns out I was using a .cfg from the previous version. Sorry.

**Comment by curzon01** [comment]
thats also possible, add flag - w to suppress warning
