### ISSUE TITLE
No module named 'configargparse', try "python -m pip install 'configargparse'" on MacOs

### ISSUE THREAD

**Issue by nospam2k** [tasmota/decode-config#25]
Installed python3 with brew.

python3 ./decode-config.py -f Config_wifi_light12_9.1.0.dmp
No module named 'ConfigArgparse', try "python -m pip install 'ConfigArgparse'"

% pip3 list
Package        Version
-------------- ---------
certifi        2020.12.5
chardet        4.0.0
ConfigArgParse 1.2.3
idna           2.10
pip            20.3.1
requests       2.25.1
setuptools     51.0.0
urllib3        1.26.2
wheel          0.36.1

I tried changing:
    import ConfigArgParse as configargparse

but no difference.

**Comment by curzon01** [comment]
Sorry, currently no Mac available, can not test.
Try what it's printing, not pip3 directly

**Comment by nospam2k** [comment]
As python is 2.7, that wouldn't work. I found if I put the configargparse.py in the same dir as decode-config, it works. So that will work around. I put in an issue with configargparse as well.
