### ISSUE TITLE
decode-config crashes with the Sonoff Zbridge

### ISSUE THREAD

**Issue by bwims** [tasmota/decode-config#27]
**Describe the bug**
decode-config crashes with the Sonoff Zbridge

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Program parameter:_ decode-config_win64 -T command -f Config_Zbridge_04C9EB_2539_9.2.0.2.dmp
_2. Result:_

'stty' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "decode-config.py", line 4940, in <module>
IndexError: list index out of range
[12600] Failed to execute script decode-config

**Expected behavior**
_A clear and concise description of what you expected to happen._

Normal output as per any other kind of sonoff/tasmota device.

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```
Script:   decode-config.py
Python:   3.6.8
Platform: Windows-10-10.0.18362-SP0 - AMD64
OS:       Windows 10 10.0.18362
Time:     2021-01-05 16:58:15
```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```
(shouldn't that say -s, not -f?)

Same crash dump as before. 

However, since this data generates info about my PC, I have created something similar.
NB This is from a DIFFERENT .dmp file (of an RF Bridge)

{"bootcount": 36, "cfg_crc": "0x5814", "cfg_holder": 4617, "cfg_size": 3584, "header": {"data": {"crc": "0x5814", "size": 3584, "template": {"crc": "0x5814", "size": 3584, "version": "0x6040112"}, "version": "0x6050000"}, "env": {"platform": "Windows-10-10.0.18362-SP0", "python": "3.6.8", "script": "decode-config.py v9.2.0 [f54a77a]", "system": "Windows AMD64 10 10.0.18362"}, "timestamp": "2021-01-05 17:02:22"}, "version": "0x6050000"}

```

**Additional context**

I realise this is a very new device, so you may not yet have had a chance to develop for it yet.

**Comment by curzon01** [comment]
need the version you use (you cut it using ` decode-config -VV` - it's the very first line like

`decode-config.py v9.2.0.3 [479011a] by Norbert Richter <nr@prsolution.eu>`

**Comment by curzon01** [comment]
The error occurs 'cause the program try to tell you you are using incompatible data:

either 
- use current patch (current dev version as python script)
- or add parameter `-w` to ignore warning:
`decode-config_win64 -T command -f Config_Zbridge_04C9EB_2539_9.2.0.2.dmp`
