### ISSUE TITLE
How to keep track of Zigbee ad-hoc configuration commands?

### ISSUE THREAD

**Issue by bwims** [tasmota/decode-config#28]
**Is your feature request related to a problem? Please describe.**

I did not realise until too late that the ZBbridge commands that configure the Zigbee appliances are "ad-hoc" and are not saved in the configuration dump.

**Describe the solution you'd like**
Presumably these changes are stored in zigbee-related flash memory somewhere.  If so, could there be a tool to save those potentially complicated configuration items?  E.g. group memberships, device friendly names, etc.

**Describe alternatives you've considered**

An article written telling us how to save these ad-hoc configurations via a series of interrogatory commands that could be cut and paste somewhere would be good.

Thanks!

**Comment by curzon01** [comment]
sorry, decode-config is depending on Tasmota config data and your request is no decode-config issue so I am not the right contact person for this.

As it is Tasmota related pls try Discord or [Discussion](https://github.com/arendst/Tasmota/discussions)
