### ISSUE TITLE
Package up and publish to pypi

### ISSUE THREAD

**Issue by inverse** [tasmota/decode-config#38]
**Is your feature request related to a problem? Please describe.**

Would be great if this could be packaged up and distributed on pypi.

This would enable users to easily install via tools like `pip` or `pipx`.

**Describe the solution you'd like**

Leveraging a tool such as poetry could help with this or you could do it manually with setup.py.

Could be easily plugged in via a GitHub action such as https://github.com/inverse/python-iolite-client/blob/master/.github/workflows/publish.yml

**Describe alternatives you've considered**

Distributing via Docker could also be a solution.

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by curzon01** [comment]
PR are welcome

**Comment by inverse** [comment]
Any objections to adopting poetry for packaging + dependency management?
