### ISSUE TITLE
[FR] Update for v.12.0.1

### ISSUE THREAD

**Issue by unclej84** [tasmota/decode-config#46]
### Describe the solution you'd like

Support for latest tasmota version (v12.0.1)

### Describe alternatives you've considered

Use `'--ignore-warnings` flag (config exported from v11.1.0) but I am not sure if this will break anything

**Comment by curzon01** [comment]
there will be as soon as there is time for it

changes are marginal, use -w until then

**Comment by curzon01** [comment]
with config from v11.1.0 this warning does not appear
or it's a config from a v12, then it's a config v12
