### ISSUE TITLE
Convert ESP8266 configuration file to ESP32 configuration file

### ISSUE THREAD

**Issue by Bascht74** [tasmota/decode-config#47]
### Is your feature request related to a problem? Please describe

I am in the process of swapping a lot of ESP8266 devices into ESP32 devices. e.g. Shelly 1/2.... to Shelly Plus. 
It would be great if the configuration could be converted here, e.g. shutter settings, setoptions, MQTT, wifi, etc. 
Currently this does not seem possible. 

### Describe the solution you'd like

Maybe you could allow it after all and leave out the GPIO configurations and set other things that are ESP8266 "only" and ESP32 default settings. This could save a lot of time when "upgrading" and only have to worry about the "specialties".

### Describe alternatives you've considered

I converted a file "manually" in the editor (I forgot what I configured, long time ago) and it was possible in many places. On the whole, many settings are identical. 

### Additional context

An alternative would be if the possible parts could be read in right away during the import into Tasmote and you get a short hint what could not be taken over. Then you can take care of it. 

The whole thing could perhaps work similar to the Fritzbox, when you migrate from an older hardware to a new one. (if known).

**Comment by curzon01** [comment]
> Currently this does not seem possible.

It's possible
- create a json backup from ESP8266
- remove key "config_version" (possibly also "header")
- restore json backup to ESP32

_Alternative_ also works if you use -w to ignore errors and in additon -v to display what was ignored.
