### ISSUE TITLE
Support version Tasmota 2022.01.3

### ISSUE THREAD

**Issue by oernii** [tasmota/decode-config#49]
### Is your feature request related to a problem? Please describe
I have a couple tasmotas with version [Tasmota 2022.01.3 by Theo Arends](https://bit.ly/tasmota).

### Describe the solution you'd like
Support this version if possible.

### Describe alternatives you've considered
A binary cfg backup

I can provide a binary cfg backup from this version

**Comment by curzon01** [comment]
Tasmota CalVer was used very short time in Tasmota dev branch. Supporting these special versions would mean a lot of effort that would be disproportionate to the benefit

Tasmota 2022.01.3 = 10.1.0.6

If you have to handle configs with this version usw -w
