### ISSUE TITLE
--output-format cmnd is crashing with no group specified.

### ISSUE THREAD

**Issue by mkaatman** [tasmota/decode-config#51]
### Describe the bug

Output as JSON works fine but when I try to specify --output-format cmnd it crashes.

I looked at the list of groups:
`(choose from 'Control', 'Display', 'Domoticz', 'Internal', 'Knx', 'Light', 'Management', 'Mqtt', 'Power', 'Rf', 'Rules', 'Sensor', 'Serial', 'Setoption', 'Shutter', 'System', 'Telegram', 'Timer', 'Wifi', 'Zigbee')`

It seems to be specific to Management as it works for most groups I've tried, but Management comes back with the same error if I add --group Management.

### To Reproduce

_1. Program parameter: decode-config.py --source 192.168.2.86 --output-format cmnd
_2. Result: 

```bash
WARNING 21 (@4692): 'gpio'
Premature exit - #21 Internal error
```

### Expected behavior

Expected a full list with no filter

### Version Information

```bash

decode-config.py v12.2.0.0 [ec10988] by Norbert Richter nr@prsolution.eu

Script:   decode-config.py
Python:   3.9.2
Platform: Linux-5.15.19-1-pve-x86_64-with-glibc2.31 - x86_64
OS:       Linux 5.15.19-1-pve #1 SMP PVE 5.15.19-1 (Fri, 04 Feb 2022 06:09:14 +0100)
Time:     2022-10-19 03:37:11

```

### System' information of your Tasmota data

```json

{
	"bootcount": 27,
	"bootcount_reset_time": 1648700436,
	"cfg_crc": "0x99ae",
	"cfg_crc32": "0x93577ccd",
	"cfg_holder": 4617,
	"cfg_size": 4096,
	"cfg_timestamp": 1665854767,
	"header": {
		"data": {
			"crc": "0xcb1",
			"crc32": "0x93577ccd",
			"hardware": "ESP82/32",
			"size": 4096,
			"version": {
				"id": "0xc010104",
				"name": "12.1.1.4"
			}
		},
		"env": {
			"platform": "Linux-5.15.19-1-pve-x86_64-with-glibc2.31",
			"python": "3.9.2",
			"script": "decode-config.py v12.2.0.0 [ec10988]",
			"system": "Linux x86_64 5.15.19-1-pve #1 SMP PVE 5.15.19-1 (Fri, 04 Feb 2022 06:09:14 +0100)"
		},
		"template": {
			"crc": "0x99ae",
			"crc32": "0x93577ccd",
			"size": 4096,
			"version": {
				"id": "0xc010103",
				"name": "12.1.1.3"
			}
		},
		"timestamp": "2022-10-15 17:26:07"
	},
	"version": "0xc010104"
}

```

### Additional context

It's working on different device that's running 12.2.0 so I tried to upgrade this problem device but it's having the same issue. This is a vont bulb if that matters. I get the same error across all of my vont bulbs (which are otherwise working fine)

**Comment by curzon01** [comment]
not reproducible - probably due to the data content
pls provide json for "gpio" or binary config (by ermail)

**Comment by mkaatman** [comment]
Sent.

**Comment by curzon01** [comment]
use latest dev
