### ISSUE TITLE
JSON output has extra characters

### ISSUE THREAD

**Issue by meingraham** [tasmota/decode-config#6]
```
    "ntp_server": [
        "openhabianpi",
        "pool.ntp.orgrg",
        "us.pool.ntp.orgg"
    ],
    "ota_url": "http://thehackbox.org/tasmota/tasmota.binff.bin",
```

Should be `.org` on 2 & 3 and just `tasmota.bin`

A clue could be that the device originally was 6.x and had the default (pre-compiled binaries and OTAURL). For example, the OTAURL was `http://thehackbox.org/tasmota/release/sonoff.bin`. So the configuration backup `dmp` must still have the remainders (`ff.bin`) of that string. May be the same for the NTP servers.

This could be the case for other strings but I just spotted these in my backup.

**Comment by curzon01** [comment]
Which version do you use (parameter -V) and which executable (python interpreter, windows or Linux exec)

**Comment by meingraham** [comment]
I upgraded the device is 7.1.2.4. The extra characters issue was there with 6.6.0.16 and with the current version. I'm using Python on Raspbian. I grabbed decode-config.py last night.

**Comment by curzon01** [comment]
possible to get the 'header'  from JSON output? e.g.
```
sudo apt install jq
./decode-config.py -d device | jq '.header'
```

**Comment by meingraham** [comment]
```json
{
  "data": {
    "crc": "0xb392",
    "crc32": "0xb55a993e",
    "size": 4096,
    "version": "0x7010204"
  },
  "format": {
    "jsoncompact": false,
    "jsonhidepw": false,
    "jsonindent": null,
    "jsonsort": true
  },
  "os": [
    "armv7l",
    "Linux",
    "4.19.66-v7+",
    "#1253 SMP Thu Aug 15 11:49:46 BST 2019",
    "Linux-4.19.66-v7+-armv7l-with-debian-9.11"
  ],
  "python": "3.5.3",
  "script": {
    "name": "decode-config.py",
    "version": "7.1.1.1 [00043]"
  },
  "template": {
    "crc": "0xb392",
    "crc32": "0xb55a993e",
    "size": 4096,
    "version": "0x7010204"
  },
  "timestamp": "2019-12-10 16:25:10"
}
```

**Comment by curzon01** [comment]
thx, will have a look...
