### ISSUE TITLE
Apparent off-by-one issue with GPIO listings in "Command" mode. [Low Priority]

### ISSUE THREAD

**Issue by PuceBaboon** [tasmota/decode-config#7]
**Describe the bug**

Listing the information from a 6.3.0.12 saved configuration file gave the GPIOs starting from GPIO1, rather than GPIO0.

**To Reproduce**

decode-config.py  -T Command  -f /path/to/saved/configs/Config_Sonoff_6.3.0.dmp

   ...produces (excerpt):-

# Management:
  Emulation 0
  FriendlyName1 TV-Switch
  FriendlyName2 TV-Switch2
  FriendlyName3 TV-Switch3
  FriendlyName4 TV-Switch4
  Gpio1 0
  Gpio2 0
  Gpio3 4
  Gpio4 0
  Gpio5 0
  Gpio6 0
  Gpio7 0
  Gpio8 0
  Gpio9 0
  Gpio10 0
  Gpio11 0
  Gpio12 0
  Gpio13 17
  Gpio14 37
  Gpio15 38
  Gpio16 39
  Gpio17 21
  Gpio18 0

**Expected behavior**

I would have expected the first GPIO to have been labelled as "GPIO0", as that's how they are labelled in the actual TASMOTA application.

In this particular instance, the DS1820 sensor (ID #4) is actually on GPIO2, not GPIO3.

**Version Information (please complete the following information):**

decode-config.py v8.1.0.1 [00063] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.9
Platform: Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
OS:       Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019
Time:     2019-12-30 16:42:41

decode-config/decode-config.py -g system --json-indent 2 -f ~/Sonoff/Config_TV_Switch_6.3.0.12" (6)".dmp
{
  "bootcount": 37, 
  "cfg_crc": "0x28ca", 
  "cfg_holder": 4619, 
  "cfg_size": 3584, 
  "displays": "0xffffffff", 
  "drivers": [
    "0xffffffff", 
    "0xffffffff", 
    "0xffffffff"
  ], 
  "energy_kWhtotal_time": 1543697777, 
  "flag": {}, 
  "flag2": {
    "axis_resolution": 0
  }, 
  "flag3": {}, 
  "header": {
    "data": {
      "crc": "0x28ca", 
      "size": 3584, 
      "version": "0x603000c"
    }, 
    "format": {
      "jsoncompact": false, 
      "jsonhidepw": false, 
      "jsonindent": 2, 
      "jsonsort": true
    }, 
    "os": [
      "x86_64", 
      "Linux", 
      "4.15.0-50-generic", 
      "#54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019", 
      "Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic"
    ], 
    "python": "3.6.9", 
    "script": {
      "name": "decode-config.py", 
      "version": "8.1.0.1 [00063]"
    }, 
    "template": {
      "crc": "0x28ca", 
      "size": 3584, 
      "version": "0x603000b"
    }, 
    "timestamp": "2019-12-30 07:47:18"
  }, 
  "last_module": 17, 
  "monitors": "0xffffffff", 
  "rgbwwTable": [
    255, 
    255, 
    255, 
    255, 
    255
  ], 
  "save_flag": 1957, 
  "sensors": [
    "0xffffffff", 
    "0xffffffff", 
    "0xffffffff"
  ], 
  "timezone_minutes": 0, 
  "version": "0x603000c"
}

**Additional context**
_Add any other context about the problem here._

Very low priority (more than ten GPIOs, so I had to take my socks off to keep count).  :-)

**Comment by PuceBaboon** [comment]
That's got to be a world record fix time!

   A thing of beauty to behold (from the same data file):-

# Management:
  Emulation 0
  ...
  Gpio0 0
  Gpio1 0
  Gpio2 4
  Gpio3 0
  ...
  Gpio11 0
  Gpio12 17
  Gpio13 37
  Gpio14 38
  Gpio15 39
  Gpio16 21
  Gpio17 0

   Thank you gentlemen.  I hope I'm not getting too much wrong:-


https://esp8266hints.wordpress.com/2019/12/30/recovering-data-from-tasmota-config-back-up-files/

   Best wishes from a cold, wet Japan,

                      -John-

**Comment by curzon01** [comment]
thx - regard your blog: the Python topic has been done since the [Releases](https://github.com/tasmota/decode-config/releases) contain binaries for all common OS
