### ISSUE TITLE
Ignore minor version changes automatically

### ISSUE THREAD

**Issue by schrej-zz** [tasmota/decode-config#74]
### Is your feature request related to a problem? Please describe

decode-config compains even about minor version changes like currently from 3.1.0.0 to 3.1.0.1

### Describe the solution you'd like

Ignore at least the last digit of the version change. It is highly unlikely, that the developers will implement a change, thas has an impact on your script in such a minor version number.

### Describe alternatives you've considered

1. Use --ignore-warnings. But this is too risky, as this will also impact major version changes. Esp. if you utilize a script by crontab
2. Enhace the ignore-warnings parameter to be (minor) version sensitive. E.g. --ignore-warnings3 to ignore changes from digit 3 downwards 

### Additional context

N/A

**Comment by curzon01** [comment]
The version number is unfortunately not an indicator of the severity of changes and the differences grow partly as a resultof the development within developer branch (just the changes of 3.1.0.0 vs 3.1.0.1 show this, here new chip types were introduced).  Some are affected very much, some not at all. The changes can be from minimal to severe depending on the hardware used and the usage scenario. So it is not so easy to make a weighting of the changes, especially not by the version numbers.

There are for example warnings when exceeding value ranges as well as warnings when using config data from unsupported (newer) versions (but these are actually always very short, I pull the versions actually quite quickly). For the two examples mentioned, a classification of the warning (enhance -w) would be useful to work around one without restricting the other warning. However, practice shows that this always complicates things, one doesn't need it at all, the other doesn't like the classifications.

I do not completely understand your request yet, even if I can think of one or two examples like above.

There are some concrete examples of this from you?

**Comment by curzon01** [comment]
BTW: The current decode-config is also not on the level of Tasmota v3.1.0.0.
With v3.1.0 the appending of the driver settings files '.drvsetxxx' was introduced by Tasmota, whose support has partly considerable (more or less) effects on the current code of decode-config. I am still in the process of implementing this (#72), the current implementation is a workaround and simply ignores this additional data. It takes time at the moment as I am busy with other things.

**Comment by curzon01** [comment]
Another example of config data strucuture changes in different (also minor changes) Tasmota versions:

It often happens that new structural elements are introduced or older deleted, here ignoring them would not be a big deal. But sometimes the addressing of already existing structure elements changes. In this case ignoring the change would lead to overwriting of memory space of unwanted other parameters.

**Comment by schrej-zz** [comment]
Hi @curzon01,
unverstanden.
Thougt, it might be also less work for you, as you do not need to update that fast.
Will close the issue.
