### ISSUE TITLE
Friendly name gets stripped of national chars

### ISSUE THREAD

**Issue by sfromis** [tasmota/decode-config#8]
**Describe the bug**
Dumping config for a Sonoff Pow R2, I see
```
  "friendlyname": [
    "Kkken fryser", 
```
Not affiliated to KKK :-) the actual friendly name is "Køkken fryser" (Kitchen freezer). Looks like chars outside of 7-bit ascii gets stripped. Same with other similar chars. This happens both when dumping to bash terminal and a file. Same when using @f to put friendly name into output file name (not translated to _).

**To Reproduce**
Configure Tasmota with such a name, and run decode-config.

**Expected behavior**
Name preserved. More generally, I'd expect UTF-8 encoding as the "natural" text file encoding.

**Version Information (please complete the following information):**
```
./decode-config.py -VV
decode-config.py v8.1.0.6 [00076] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.9
Platform: Linux-4.15.0-76-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
OS:       Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
Time:     2020-02-20 10:34:17
```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```
{
  "bootcount": 11, 
  "cfg_crc": "0xdfda", 
  "cfg_crc32": "0xbdc51bb5", 
  "cfg_holder": 4617, 
  "cfg_size": 4096, 
  "cfg_timestamp": 1582153201, 
  "displays": "0xffffffff", 
  "energy_kWhtotal_time": 1579286020, 
  "flag2": {
    "axis_resolution": 0
  }, 
  "flag4": "0x00000000", 
  "header": {
    "data": {
      "crc": "0xde3a", 
      "crc32": "0xbdc51bb5", 
      "size": 4096, 
      "version": "0x8010000"
    }, 
    "format": {
      "jsoncompact": false, 
      "jsonhidepw": false, 
      "jsonindent": 2, 
      "jsonsort": true
    }, 
    "os": [
      "x86_64", 
      "Linux", 
      "4.15.0-76-generic", 
      "#86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020", 
      "Linux-4.15.0-76-generic-x86_64-with-Ubuntu-18.04-bionic"
    ], 
    "python": "3.6.9", 
    "script": {
      "name": "decode-config.py", 
      "version": "8.1.0.6 [00076]"
    }, 
    "template": {
      "crc": "0xdfda", 
      "crc32": "0xbdc51bb5", 
      "size": 4096, 
      "version": "0x8010000"
    }, 
    "timestamp": "2020-02-19 23:00:01"
  }, 
  "last_module": 0, 
  "monitors": "0xffffffff", 
  "rgbwwTable": [
    255, 
    255, 
    255, 
    255, 
    255
  ], 
  "save_flag": 109, 
  "sps30_inuse_hours": 0, 
  "timezone_minutes": 0, 
  "version": "0x8010000"
}
```

**Additional context**

**Comment by sfromis** [comment]
Thanks, it works for me.

I was a bit surprised to see the ø escaped into \u00f8 instead of just being left in regular UTF-8, but as both are valid JSON, no problem :-)

**Comment by curzon01** [comment]
it's a json dump default - see last commit

**Comment by sfromis** [comment]
Great, that tweak made it more friendly to human readers, especially for languages not based on a latin alphabet.

**Comment by curzon01** [comment]
initial reason of the filter were if you e.g. upgrade/downgrade tasmota sometimes I've found binary garbadge within strings (which then tried to interpret as useless uft8). This can still happen but in normal circumstance it's ok.
