### ISSUE TITLE
Missing module setting in the JSON file for ESP32-C3 ("config_version": 4)

### ISSUE THREAD

**Issue by Papablaubaer** [tasmota/decode-config#83]
### Describe the bug

When I read out my ShellyMiniG3 with the current version as Json, the setting for the current module ("module": 255) to set the UserTemplate is missing. Neither reading nor writing works. This works perfectly on other hardware platforms ("config_version": 0 and "config_version": 1). Saving and restoring directly from Tasmota works.

### Version Information

_Please complete the following information_  
_use `decode-config.py -V --debug` to retrieve the info_

```bash

>>>Script:   decode-config.py
Version:  13.3.0.2 [384bf6b]
Python:   3.10.8
Platform: Windows-10-10.0.22000-SP0 - AMD64
OS:       Windows 10 10.0.22000
Time:     2024-01-15 17:47:44
<<<

**Comment by curzon01** [comment]
should be solved, give it a try

**Comment by Papablaubaer** [comment]
Unfortunately nothing has changed with version 13.0.0.3 the result is the same

**Comment by curzon01** [comment]
could you provide me a dmp file from your  ShellyMiniG3 (e.g per mail)?

**Comment by Papablaubaer** [comment]
Gerade ist mir aufgefallen, das es mit der neuesten Version auch nicht mehr mit 16Bit ESP funktioniert.

**Comment by curzon01** [comment]
sorry, was a typo within fix - use the latest dev (the version number of decode-config without the build in square brackets [ ]  is not an inidicator because these are always in sync with tasmota)

**Comment by Papablaubaer** [comment]
With the new version it works. Thank you for your efforts.
